//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETSOAP_METHODS.MedmarDEMOSeviceR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MedmarDEMOSeviceR.MedmarSSoap")]
    public interface MedmarSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse HelloWorld(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse> HelloWorldAsync(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name PeroResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pero", ReplyAction="*")]
        GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse Pero(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pero", ReplyAction="*")]
        System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse> PeroAsync(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pero", Namespace="http://tempuri.org/", Order=0)]
        public GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequestBody Body;
        
        public PeroRequest() {
        }
        
        public PeroRequest(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PeroRequestBody {
        
        public PeroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PeroResponse", Namespace="http://tempuri.org/", Order=0)]
        public GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponseBody Body;
        
        public PeroResponse() {
        }
        
        public PeroResponse(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PeroResult;
        
        public PeroResponseBody() {
        }
        
        public PeroResponseBody(string PeroResult) {
            this.PeroResult = PeroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MedmarSSoapChannel : GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedmarSSoapClient : System.ServiceModel.ClientBase<GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap>, GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap {
        
        public MedmarSSoapClient() {
        }
        
        public MedmarSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedmarSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedmarSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedmarSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap.HelloWorld(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest inValue = new GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest();
            inValue.Body = new GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequestBody();
            GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse retVal = ((GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse> GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap.HelloWorldAsync(GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldResponse> HelloWorldAsync() {
            GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest inValue = new GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequest();
            inValue.Body = new GETSOAP_METHODS.MedmarDEMOSeviceR.HelloWorldRequestBody();
            return ((GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap.Pero(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest request) {
            return base.Channel.Pero(request);
        }
        
        public string Pero() {
            GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest inValue = new GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest();
            inValue.Body = new GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequestBody();
            GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse retVal = ((GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap)(this)).Pero(inValue);
            return retVal.Body.PeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse> GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap.PeroAsync(GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest request) {
            return base.Channel.PeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<GETSOAP_METHODS.MedmarDEMOSeviceR.PeroResponse> PeroAsync() {
            GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest inValue = new GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequest();
            inValue.Body = new GETSOAP_METHODS.MedmarDEMOSeviceR.PeroRequestBody();
            return ((GETSOAP_METHODS.MedmarDEMOSeviceR.MedmarSSoap)(this)).PeroAsync(inValue);
        }
    }
}
